### ISSUE TITLE
Something is not working again, something with the header, yesterday all was fine

### ISSUE THREAD

**Issue by Myocastor** [nolanaatama/sd-1click-colab#19]
Installing pycloudflared

Launching Web UI with arguments: --share --disable-safe-unpickle --no-half-vae --xformers --enable-insecure-extension- --gradio-queue --remotemoe
2023-03-10 17:48:08.942515: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-10 17:48:11.816804: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.9/dist-packages/cv2/../../lib64:/usr/lib64-nvidia
2023-03-10 17:48:11.817220: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.9/dist-packages/cv2/../../lib64:/usr/lib64-nvidia
2023-03-10 17:48:11.817252: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
remote.moe detected, trying to connect...
Warning: Permanently added 'remote.moe,159.69.126.209' (ECDSA) to the list of known hosts.
Calculating sha256 for /content/stable-diffusion-webui/models/Stable-diffusion/abyssorangemix3A1.safetensors: f36668ddf22403a332f978057d527cf285b01468bc3431b04094a7bafa6aba59
Loading weights [f36668ddf2] from /content/stable-diffusion-webui/models/Stable-diffusion/abyssorangemix3A1.safetensors
loading stable diffusion model: SafetensorError
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/webui.py", line 111, in initialize
    modules.sd_models.load_model()
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 383, in load_model
    state_dict = get_checkpoint_state_dict(checkpoint_info, timer)
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 238, in get_checkpoint_state_dict
    res = read_state_dict(checkpoint_info.filename)
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 217, in read_state_dict
    pl_sd = safetensors.torch.load_file(checkpoint_file, device=device)
  File "/usr/local/lib/python3.9/dist-packages/safetensors/torch.py", line 99, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

Stable diffusion model failed to load, exiting

**Comment by nolanaatama** [comment]
updated. thank you for the heads up mate!
