### ISSUE TITLE
still having errors; does not load model

### ISSUE THREAD

**Issue by potato8382** [nolanaatama/sd-1click-colab#20]
Tried using abyssorangemix3a3 and in the ui, the only option for the model is v1-5-pruned-emaonly.safetensors

Tried to manually install the correct model and others, but when trying to switch in the UI, it returns "HeaderTooLarge" and stays on the emaonly.

Edit: This is just a problem on the individual abyssorangemix3a3, just realised the newer ones added work fine. Possibly delete the individual one to remove the faulty clutter.

**Comment by potato8382** [comment]
When trying to switch:

Calculating sha256 for /content/stable-diffusion-webui/models/Stable-diffusion/abyssorangemix3a3.safetensors: f36668ddf22403a332f978057d527cf285b01468bc3431b04094a7bafa6aba59
Loading weights [f36668ddf2] from /content/stable-diffusion-webui/models/Stable-diffusion/abyssorangemix3a3.safetensors
changing setting sd_model_checkpoint to abyssorangemix3a3.safetensors: SafetensorError
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/shared.py", line 554, in set
    self.data_labels[key].onchange()
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "/content/stable-diffusion-webui/webui.py", line 120, in <lambda>
    shared.opts.onchange("sd_model_checkpoint", wrap_queued_call(lambda: modules.sd_models.reload_model_weights()))
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 464, in reload_model_weights
    state_dict = get_checkpoint_state_dict(checkpoint_info, timer)
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 238, in get_checkpoint_state_dict
    res = read_state_dict(checkpoint_info.filename)
  File "/content/stable-diffusion-webui/modules/sd_models.py", line 217, in read_state_dict
    pl_sd = safetensors.torch.load_file(checkpoint_file, device=device)
  File "/usr/local/lib/python3.9/dist-packages/safetensors/torch.py", line 99, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

**Comment by nolanaatama** [comment]
updated and fixed. thanks for the heads up mate!
