### ISSUE TITLE
Issue: Gradio related error

### ISSUE THREAD

**Issue by OfficialDSplayer** [nolanaatama/sd-1click-colab#32]
Running the launch.py with the command line arguments results in errors from Gradio which causes the Error popup to show on almost every setting.

`Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1018, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 947, in postprocess_data
    prediction_value = postprocess_update_dict(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 371, in postprocess_update_dict
    update_dict = block.get_specific_update(update_dict)
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 257, in get_specific_update
    specific_update = cls.update(**generic_update)
TypeError: update() got an unexpected keyword argument 'multiline'`

A person on the r/StableDiffusion subreddit is also having a similar issue: https://www.reddit.com/r/StableDiffusion/comments/12bk7sd/do_anyone_know_to_solve_this_issue_while_using_sd/

**Comment by OfficialDSplayer** [comment]
This seemed to be caused by the DominikDoom's a1111-sd-webui-tagcomplete. Commenting that out seemed to solve that issue.
