### ISSUE TITLE
so this is what is wrong

### ISSUE THREAD

**Issue by angelmingkem93** [nolanaatama/sd-1click-colab#34]
Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 0cc0ee1b Merge pull request #7945 from w-e-w/fix-image-downscale
Cloning into 'embeddings'...
remote: Enumerating objects: 44, done.
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 44 (delta 8), reused 0 (delta 0), pack-reused 19
Unpacking objects: 100% (44/44), 5.96 KiB | 1017.00 KiB/s, done.
Filtering content: 100% (19/19), 929.03 KiB | 769.00 KiB/s, done.
Python 3.9.16 (main, Dec  7 2022, 01:11:51) 
[GCC 9.4.0]
Commit hash: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8
Installing gfpgan
Installing clip
Installing open_clip
Installing xformers
Cloning Stable Diffusion into repositories/stable-diffusion-stability-ai...
Cloning Taming Transformers into repositories/taming-transformers...
Cloning K-diffusion into repositories/k-diffusion...
Cloning CodeFormer into repositories/CodeFormer...
Cloning BLIP into repositories/BLIP...
Installing requirements for CodeFormer
Installing requirements for Web UI
Installing pycloudflared

Installing sd-webui-controlnet requirement: svglib

Launching Web UI with arguments: --share --disable-safe-unpickle --no-half-vae --xformers --enable-insecure-extension- --gradio-queue --remotemoe
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/launch.py", line 361, in <module>
    start()
  File "/content/stable-diffusion-webui/launch.py", line 352, in start
    import webui
  File "/content/stable-diffusion-webui/webui.py", line 15, in <module>
    from modules import import_hook, errors, extra_networks, ui_extra_networks_checkpoints
  File "/content/stable-diffusion-webui/modules/ui_extra_networks_checkpoints.py", line 6, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "/content/stable-diffusion-webui/modules/shared.py", line 12, in <module>
    import modules.interrogate
  File "/content/stable-diffusion-webui/modules/interrogate.py", line 11, in <module>
    from torchvision import transforms
  File "/usr/local/lib/python3.9/dist-packages/torchvision/__init__.py", line 6, in <module>
    from torchvision import datasets, io, models, ops, transforms, utils
  File "/usr/local/lib/python3.9/dist-packages/torchvision/datasets/__init__.py", line 1, in <module>
    from ._optical_flow import FlyingChairs, FlyingThings3D, HD1K, KittiFlow, Sintel
  File "/usr/local/lib/python3.9/dist-packages/torchvision/datasets/_optical_flow.py", line 12, in <module>
    from ..io.image import _read_png_16
  File "/usr/local/lib/python3.9/dist-packages/torchvision/io/__init__.py", line 8, in <module>
    from ._load_gpu_decoder import _HAS_GPU_VIDEO_DECODER
  File "/usr/local/lib/python3.9/dist-packages/torchvision/io/_load_gpu_decoder.py", line 1, in <module>
    from ..extension import _load_library
  File "/usr/local/lib/python3.9/dist-packages/torchvision/extension.py", line 107, in <module>
    _check_cuda_version()
  File "/usr/local/lib/python3.9/dist-packages/torchvision/extension.py", line 80, in _check_cuda_version
    raise RuntimeError(
RuntimeError: Detected that PyTorch and torchvision were compiled with different CUDA versions. PyTorch has CUDA Version=11.7 and torchvision has CUDA Version=11.8. Please reinstall the torchvision that matches your PyTorch install.

**Comment by OfficialDSplayer** [comment]
Add. `!pip install torch==1.13.1+cu116 torchvision==0.14.1+cu116 torchaudio==0.13.1 torchtext==0.14.1 torchdata==0.5.1 --extra-index-url https://download.pytorch.org/whl/cu116 -U` to the first cell after `!pip install --upgrade fastapi==0.90.1` (this is included in Nolan's updated notebook versions). Google Colab updated PyTorch or Torchvision and they became incompatible.

**Comment by angelmingkem93** [comment]
what is the solution?

**Comment by OfficialDSplayer** [comment]
> what is the solution?

If you want to keep your notebook without replacing it, add the line of code like seen here: 
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/66536577/230182923-4603d3aa-189a-43c6-a9f1-caa2f1c2bd63.png">

If you don't mind updating your notebook, just download the latest version from Nolan.
